version: '3.6'

services:
  web:
    build:
      context: docker/build/nginx
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_SERVER_NAME
      - NGINX_ENABLE_SSL
      - NGINX_FORCE_HTTPS
      - APP_CONTAINER_NAME
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - ./docker/storage/nginx/certs:/etc/nginx/certs
      - ./laravel-app:/var/www/html/laravel-app:delegated
      - ./phpmyadmin:/var/www/html/phpmyadmin:delegated
    depends_on:
      - app
    networks:
      - default
      - laravel-shared

  app:
    build:
      context: docker/build/app
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    environment:
      - APP_URL
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_CONTAINER_NAME}
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - MAIL_MAILER=smtp
      - MAIL_HOST=${MAIL_CONTAINER_NAME}
      - MAIL_PORT=1025
      - MAIL_FROM_ADDRESS=${APP_EMAIL}
      - MAIL_FROM_NAME=Laravel
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - ./laravel-app:/var/www/html/laravel-app:delegated
      - ./phpmyadmin:/var/www/html/phpmyadmin:delegated
      - ./docker/storage/app/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
    depends_on:
      - db
    networks:
      - default
      - laravel-shared

  db:
    build:
      context: docker/build/mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - ./docker/storage/mysql/data:/var/lib/mysql
      - ./docker/storage/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf:cached
    networks:
      - default
      - laravel-shared

  mail:
    build:
      context: docker/build/mail
      dockerfile: Dockerfile
    container_name: ${MAIL_CONTAINER_NAME}
    ports:
      - "8025:8025"
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - maildir:/data
    depends_on:
      - app
    networks:
      - default
      - laravel-shared

volumes:
  maildir:

networks:
  laravel-shared:
    external: true